### DELETE un film
DELETE http://localhost:3000/films/2
Content-Type: application/json

### PATCH un film
PATCH http://localhost:3000/films/1
Content-Type: application/json

{
  "title": "Inception Updated",
  "budget": 170
}

### PUT un film existant (remplacement complet)
PUT http://localhost:3000/films/1
Content-Type: application/json

{
  "title": "Inception Replaced",
  "director": "Christopher Nolan",
  "duration": 150,
  "budget": 175
}

### PUT film non existant (création)
PUT http://localhost:3000/films/10
Content-Type: application/json

{
  "title": "New Movie",
  "director": "Some Director",
  "duration": 120,
  "budget": 50
}
